NAME: nfs-client-provisioner
LAST DEPLOYED: Tue Mar 15 12:04:01 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
null

COMPUTED VALUES:
affinity: {}
image:
  pullPolicy: IfNotPresent
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
imagePullSecrets: []
labels: {}
leaderElection:
  enabled: true
nfs:
  mountOptions: null
  path: /export/itk8s/
  reclaimPolicy: Delete
  server: 172.16.100.59
  volumeName: nfs-subdir-external-provisioner-root
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
podSecurityPolicy:
  enabled: false
rbac:
  create: true
replicaCount: 3
resources: {}
securityContext: {}
serviceAccount:
  annotations: {}
  create: true
  name: null
storageClass:
  accessModes: ReadWriteMany
  allowVolumeExpansion: true
  annotations: {}
  archiveOnDelete: false
  create: true
  defaultClass: false
  name: nfs-client
  onDelete: null
  pathPattern: null
  reclaimPolicy: Delete
strategyType: Recreate
tolerations: []

HOOKS:
MANIFEST:
---
# Source: nfs-subdir-external-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: nfs-client-provisioner-nfs-subdir-external-provisioner
---
# Source: nfs-subdir-external-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: nfs-client
  annotations:
provisioner: cluster.local/nfs-client-provisioner-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
---
# Source: nfs-subdir-external-provisioner/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: nfs-client-provisioner-nfs-subdir-external-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
# Source: nfs-subdir-external-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: run-nfs-client-provisioner-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-nfs-subdir-external-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-nfs-subdir-external-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-subdir-external-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: leader-locking-nfs-client-provisioner-nfs-subdir-external-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: nfs-subdir-external-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
  name: leader-locking-nfs-client-provisioner-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-nfs-subdir-external-provisioner
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner-nfs-subdir-external-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-subdir-external-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner-nfs-subdir-external-provisioner
  labels:
    chart: nfs-subdir-external-provisioner-4.0.15
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: nfs-client-provisioner
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-client-provisioner
  template:
    metadata:
      annotations:
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner-nfs-subdir-external-provisioner
      securityContext:
        {}
      containers:
        - name: nfs-subdir-external-provisioner
          image: "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-client-provisioner-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 172.16.100.59
            - name: NFS_PATH
              value: /export/itk8s/
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: 172.16.100.59
            path: /export/itk8s/

