apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-demo
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx-demo
  namespace: brh
spec:
  rules:
  - host: nginx.demo5.proxym-it.tn
    http:
      paths:
      - backend:
          service:
            name: nginx-deploy-main
            port:
              number: 80
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 172.16.10.213

