apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-qa
    meta.helm.sh/release-namespace: nginx-ingress
  labels:
    app.kubernetes.io/instance: nginx-qa
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-qa-nginx-ingress
    helm.sh/chart: nginx-ingress-0.9.3
  name: nginx-qa-nginx-ingress
  namespace: nginx-ingress
#  resourceVersion: "5505774"
 # uid: 842467e3-0eab-45ce-b49d-4e8c11a4e7ce
#secrets:
#- name: nginx-qa-nginx-ingress-token-wq54h

