apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvol-nfs

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 172.16.100.59
    path: "/export/TGO"
