apiVersion: v1
data:
  nginx.conf: "worker_processes 1; \n\nevents {\n    worker_connections 1024;\n}\nhttp
    {\n    server {\n        listen 80;\n        gzip on;\n        gzip_vary on;\n
    \       gzip_comp_level 6;\n        expires max;\n        add_header Cache-Control
    public;\n        add_header Last-Modified \"\";\n        add_header ETag \"\";\n
    \       gzip_min_length 10240;\n        gzip_proxied any;\n        gzip_http_version
    1.1;\n        # gzip_proxied expired no-cache no-store private auth;\n        gzip_types
    text/css text/javascript text/plain text/html application/json text/js application/javascript
    text/xml application/xml;\n        # gzip_disable “MSIE [1-6].(?!.*SV1)”;\n        gzip_disable
    \"msie6\";\n        gzip_buffers  16 8k;\n        server_name _;\n        root
    /usr/share/nginx/html;\n        index index.html index.htm;\n        client_max_body_size
    200M;\n        include /etc/nginx/mime.types;\n        location / {\n            try_files
    $uri $uri/ /index.html;\n            gzip_static on;\n            gzip on;\n            gzip_types
    text/css text/javascript text/plain text/html application/json text/js application/javascript
    text/xml application/xml;\n\n        }\n        \n        error_page   500 502
    503 504  /50x.html;\n            location = /50x.html {\n            root   /usr/share/nginx/html;\n
    \       }\n\n    }\n}\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: albaraka-front-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: angular
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: angular-0.3.0
  name: barwa-corp-front-dev
  namespace: ns-prx-7
