apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
 affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
 containers:
 - name: dnsutils
   image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
   command:
     - sleep
     - "3600"
   imagePullPolicy: IfNotPresent
#  restartPolicy: Always
