apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    controller-revision-hash: keycloak-6489fd68c8
    helm.sh/chart: keycloak-2.1.1
    statefulset.kubernetes.io/pod-name: keycloak-0
    velero.io/backup-name: shared-apps-28022022-lts3
    velero.io/restore-name: shared-apps-28022022-lts3-20220228131226
  name: keycloak-node-port
  namespace: ns-prx-10
spec:
  type: NodePort      
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-2.1.1
    statefulset.kubernetes.io/pod-name: keycloak-0
  sessionAffinity: None
