apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-28T12:12:35Z"
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    controller-revision-hash: keycloak-6489fd68c8
    helm.sh/chart: keycloak-2.1.1
    statefulset.kubernetes.io/pod-name: keycloak-0
    velero.io/backup-name: shared-apps-28022022-lts3
    velero.io/restore-name: shared-apps-28022022-lts3-20220228131226
  name: keycloak
  namespace: ns-prx-10
  resourceVersion: "15024767"
  uid: 7cbd5f87-d51c-4419-b6d6-dc3d1a4f02a0
spec:
  clusterIP: 10.233.6.91
  clusterIPs:
  - 10.233.6.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-2.1.1
    statefulset.kubernetes.io/pod-name: keycloak-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
