apiVersion: v1
data:
  nginx.conf: "worker_processes 1; \nevents {\n    worker_connections 1024;\n}\nhttp
    {\n    server {\n        listen 80;\n        server_name _;\n        root /usr/share/nginx/html;\n
    \       index index.html index.htm;\n        client_max_body_size 200M;\n        include
    /etc/nginx/mime.types;\n        location / {\n            try_files $uri $uri/
    /index.html;\n        }\n        \n        error_page   500 502 503 504  /50x.html;\n
    \           location = /50x.html {\n            root   /usr/share/nginx/html;\n
    \       }\n    }\n}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"worker_processes 1; \nevents {\n    worker_connections 1024;\n}\nhttp {\n    server {\n        listen 80;\n        server_name _;\n        root /usr/share/nginx/html;\n        index index.html index.htm;\n        client_max_body_size 200M;\n        include /etc/nginx/mime.types;\n        location / {\n            try_files $uri $uri/ /index.html;\n        }\n        \n        error_page   500 502 503 504  /50x.html;\n            location = /50x.html {\n            root   /usr/share/nginx/html;\n        }\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"adib-front-dev","namespace":"fsi"}}
  creationTimestamp: "2022-02-07T11:43:15Z"
  name: barwa-corp-front-dev
  namespace: ns-prx-7

