apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-demo
    meta.helm.sh/release-namespace: nginx-ingress
  labels:
    app.kubernetes.io/instance: nginx-demo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-demo-nginx-ingress
    helm.sh/chart: nginx-ingress-0.9.3
  name: nginx-demo-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-demo-nginx-ingress
subjects:
- kind: ServiceAccount
  name: nginx-demo-nginx-ingress
  namespace: nginx-ingress
