apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: ns-prx-1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: django-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: django-app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: django-app-env
        image: gitlab-registry.proxym-group.net/ahmed.belghith/pfe-k8smgmt:latest
        imagePullPolicy: Always
        name: django-app
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-auth
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
