apiVersion: v1
kind: Service
metadata:
  name: my-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: my-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dev
spec:
  selector:
    matchLabels:
      app: my-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: my-dev
    spec:
      containers:
      - name: my-app-container
        image: hashicorp/http-echo
        args:
        - "-text=hello from .dev "
        ports:
        - containerPort: 5678
