apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: shared-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
#  volumeMode: Filesystem
 # volumeName: pvc-e8567243-3819-437e-8361-a6417b36906b
