apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holahola2
  namespace: ns-prx-9
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  #volumeMode: Filesystem
  #volumeName: pvc-83bbfafb-4f91-4aaa-9b23-579b42efc42b
